/**
 * Data Transfer Objects. For this example the name of the package is arbitrary but in this case it
 * reflects a typical package name auto-generated by a WSDL-to-java tool.
 * 
 * @author bgiles
 */
package com.coyotesong.demo.cxf.namespace.helloworldservice.general;